"""Build the Chores dashboard config (examples/chores-dashboard.yaml).

Each chore becomes a Bubble Card slider button: the bar is the chore's progress
sensor, the subheading is chore_due_text, and tapping marks the chore done.
"""

import json
from pathlib import Path

import yaml

# name, Chore Calendar sensor, progress sensor, icon, bar colour, cycle days (None = interval)
CHORES = [
    ("Mow the Lawn", "sensor.chores_mow_the_lawn", "sensor.mow_the_lawn_progress", "mdi:mower", "#a0784f", 7),
    ("Take Out Trash", "sensor.chores_take_out_trash", "sensor.take_out_trash_progress", "mdi:trash-can-outline", "#a8457a", 7),
    ("Water Plants", "sensor.chores_water_plants", "sensor.water_plants_progress", "mdi:watering-can", "#4f7fae", None),
    ("Change HVAC Filter", "sensor.chores_change_hvac_filter", "sensor.change_hvac_filter_progress", "mdi:air-filter", "#5f8f6a", None),
    ("Clean Gutters", "sensor.chores_clean_gutters", "sensor.clean_gutters_progress", "mdi:home-roof", "#7d68a8", None),
]


def chore_card(name, chore, progress, icon, colour, days):
    args = f"'{chore}', {days}" if days else f"'{chore}'"
    complete = {
        "action": "perform-action",
        "perform_action": "chore_calendar.complete_item",
        "data": {"entity_id": chore},
    }
    details = {"action": "more-info", "entity": chore}
    return {
        "type": "custom:bubble-card",
        "card_type": "button",
        "button_type": "slider",
        "entity": progress,
        "name": name,
        "icon": icon,
        "read_only_slider": True,
        "slider_value_position": "hidden",
        "state_content": "{% from 'chore_tracker.jinja' import chore_due_text %}"
        "{{ chore_due_text(" + args + ") }}",
        "tap_action": complete,
        "hold_action": details,
        "button_action": {"tap_action": complete, "hold_action": details},
        "styles": ".bubble-range-fill {\n  background: " + colour + " !important;\n  opacity: 1 !important;\n}\n",
        "grid_options": {"columns": 6},
    }


config = {
    "title": "Chores",
    "views": [
        {
            "title": "Chores",
            "path": "chores",
            "icon": "mdi:broom",
            "type": "sections",
            "max_columns": 2,
            "sections": [
                {
                    "type": "grid",
                    "column_span": 2,
                    "cards": [
                        {
                            "type": "heading",
                            "heading": "Chores",
                            "heading_style": "title",
                            "icon": "mdi:broom",
                        },
                        {
                            "type": "heading",
                            "heading": "Tap a chore when it's done · hold for details",
                            "heading_style": "subtitle",
                        },
                        *[chore_card(*c) for c in CHORES],
                    ],
                }
            ],
        }
    ],
}

out = Path(__file__).resolve().parent.parent / "examples"
(out / "chores-dashboard.yaml").write_text(
    "# Full Chores dashboard (generated by scripts/build_dashboard.py).\n"
    "# Dashboard → ⋮ → Edit → ⋮ → Raw configuration editor, then paste.\n\n"
    + yaml.safe_dump(config, sort_keys=False, allow_unicode=True, width=200)
)
print(json.dumps(config))
